

spring:
  # main:
  #   allow-circular-references: true
  profiles:
    include: database

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /api

logging:
  level:
    ROOT: INFO
    com.encora.office.app: DEBUG
    org.mongodb.driver.cluster: ERROR
    org.mongodb.driver.protocol.command: ERROR


jwt:
  expiration: 86400000 # Expiration time in ms (24h)
  signature-algorithm: HS512


office:
  name: Oficina Merida
  spots: 30
  schedule:
    start-hour: 7
    end-hour: 21